import {test,expect,Page} from '@playwright/test';
test.use({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,viewport:{width:1440,height:1000}});
const url='/prototype/one-to-one-reference/team-only-app.html?edition=personal&personal=1';
async function settings(page:Page){await page.locator('#user-card').click();await expect(page.locator('#ws-menu [data-ws-action=settings]')).toHaveText('个人设置');await page.locator('#ws-menu [data-ws-action=settings]').click();await expect(page.locator('#personal-settings')).toBeVisible();await expect(page.locator('#ws-view')).toBeHidden();await expect(page.locator('#page-crumb')).toHaveText('个人设置');await expect(page.locator('[data-settings-action=configure], [data-settings-config]')).toHaveCount(0);}
async function switchTo(page:Page,id:string){await page.locator('#ws-switcher').click();await page.locator(`#ws-menu [data-ws-action=switch][data-value=${id}]`).click();}
async function capture(page:Page,name:string){if(process.env.PRD_CAPTURE){await expect(page.locator('#ws-toast')).not.toBeVisible();await expect(page.locator('#toast')).not.toBeVisible();await page.screenshot({path:`src/prototype/prd/images/${name}.png`});}}
test('account preferences share one functional page across Personal, Team admin and member',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await settings(page);await capture(page,'personal-settings');await page.locator('[data-settings-language=asr]').selectOption('zh-Hans');await page.locator('[data-settings-action=toggle-summary]').click();await expect(page.locator('[data-settings-summary-copy]')).toHaveText('已关闭自动摘要');
 await switchTo(page,'team-eureka');await page.locator('#ws-team-nav [data-value=billing]').click();await page.locator('.ws-tabs [data-value=settings]').click();await expect(page.locator('.ws-tabs')).toContainText('空间设置');await expect(page.locator('.ws-tabs')).not.toContainText('通用设置');await expect(page.locator('#ws-view h1')).toHaveText('空间设置');await capture(page,'team-settings');const name=await page.locator('[data-ws-form=settings] [name=name]').inputValue();
 await settings(page);await expect(page.locator('#ws-switcher')).toContainText('EurekaMind 产品团队');await expect(page.locator('[data-settings-language=asr]')).toHaveValue('zh-Hans');await expect(page.locator('[data-settings-action=toggle-summary]')).toHaveAttribute('aria-checked','false');await expect(page.locator('#personal-settings')).not.toContainText('工作空间名称');await capture(page,'team-personal-settings');await page.locator('[data-settings-language=asr]').selectOption('en');await page.locator('[data-settings-close]').click();await expect(page.locator('#ws-view')).toBeVisible();await expect(page.locator('#personal-settings')).toBeHidden();await expect(page.locator('#ws-view')).toContainText('团队会议');
 await page.locator('#ws-team-nav [data-value=billing]').click();await page.locator('.ws-tabs [data-value=settings]').click();await expect(page.locator('[data-ws-form=settings] [name=name]')).toHaveValue(name);
 await switchTo(page,'team-design');await expect(page.locator('#ws-team-nav')).not.toContainText('空间管理');await settings(page);await expect(page.locator('[data-settings-language=asr]')).toHaveValue('en');await page.locator('[data-settings-language=notes]').selectOption('zh-Hans');await page.reload();await settings(page);await expect(page.locator('[data-settings-action=toggle-summary]')).toHaveAttribute('aria-checked','false');await expect(page.locator('[data-settings-language=notes]')).toHaveValue('zh-Hans');await page.locator('[data-settings-close]').click();await expect(page.locator('#ws-view')).toBeVisible();await expect(page.locator('#ws-switcher')).toContainText('设计共创空间');await switchTo(page,'personal');await settings(page);await expect(page.locator('[data-settings-language=notes]')).toHaveValue('zh-Hans');await page.locator('[data-settings-close]').click();await expect(page.locator('#today-assets-grid')).toBeVisible();expect(errors).toEqual([]);
});
test('compact preferences remain usable at desktop and phone widths in either workspace',async({page})=>{
 await page.goto(url);for(const space of ['personal','team-eureka']){await switchTo(page,space);await settings(page);for(const width of [1440,1024,390]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);const panel=page.locator('#personal-settings');expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBeTruthy();await page.locator('[data-settings-language=notes]').selectOption('en');await expect(page.locator('[data-settings-language=notes]')).toHaveValue('en');await page.locator('[data-settings-close]').scrollIntoViewIfNeeded();await expect(page.locator('[data-settings-close]')).toBeInViewport();}await page.setViewportSize({width:1440,height:1000});}
});
test('account plan follows the active team, subscription status and personal workspace',async({page})=>{
 await page.goto(url);await settings(page);await expect(page.locator('.settings-profile small')).toHaveText('标准版 · 个人工作空间');await expect(page.locator('.settings-usage')).toContainText('400 分钟');
 for(const [id,name,role] of [['team-eureka','EurekaMind 产品团队','管理员'],['team-design','设计共创空间','成员']]){
  await switchTo(page,id);await settings(page);await expect(page.locator('.settings-profile small')).toHaveText(`Team Unlimited · ${name} · ${role}`);await expect(page.locator('.settings-usage')).toContainText('Unlimited · 不限时长');await expect(page.locator('.settings-usage')).not.toContainText('400');await expect(page.locator('.settings-profile strong')).toHaveText('zhang.wei@eureka.example');
 }
 await page.evaluate(()=>{const key='eureka:workspaces:v2',data=JSON.parse(localStorage.getItem(key)!);data.spaces.find((s:{id:string})=>s.id==='team-design').status='expired';localStorage.setItem(key,JSON.stringify(data));});await page.reload();await settings(page);await expect(page.locator('.settings-usage')).toContainText('转写权益已暂停');await expect(page.locator('.settings-usage')).toContainText('团队订阅已到期');
 await switchTo(page,'personal');await settings(page);await expect(page.locator('.settings-profile small')).toHaveText('标准版 · 个人工作空间');await expect(page.locator('.settings-usage')).toContainText('剩余 400 分钟');
});
