import {test,expect} from '@playwright/test';
test.use({channel:process.env.PLAYWRIGHT_CHANNEL||undefined});
const url='/prototype/one-to-one-reference/team-only-app.html?edition=personal&personal=1';
test('team new task detaches history and starts independent conversations in home and meeting',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto(url);await page.locator('#ws-switcher').click();await page.locator('#ws-menu [data-value=team-eureka]').click();await page.locator('#ws-history [data-ws-action=history]').first().click();
 const rail=page.locator('.ws-agent'),input=rail.locator('textarea');const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('eureka:workspaces:v2')!).spaces.find((w:{id:string})=>w.id==='team-eureka').threads);
 await rail.getByRole('button',{name:'新建任务',exact:true}).click();await expect(rail.locator('.ws-chat-user')).toHaveCount(0);await expect(input).toHaveValue('');await expect(input).toBeFocused();await expect(page.locator('#ws-history [data-ws-action=history]')).toHaveCount(1);
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('eureka:workspaces:v2')!).spaces.find((w:{id:string})=>w.id==='team-eureka').threads)).toEqual(before);
 if(process.env.PRD_CAPTURE){await expect(page.locator('#ws-toast')).toBeHidden();await page.mouse.move(900,100);await page.screenshot({path:'src/prototype/prd/images/agent-new-task-team.png'});}
 await input.fill('新任务：整理交付计划');await input.press('Enter');await expect(rail.locator('.ws-chat-user')).toHaveCount(1);await expect(page.locator('#ws-history [data-ws-action=history]')).toHaveCount(2);
 await rail.getByRole('button',{name:'新建任务',exact:true}).click();await expect(rail.locator('.ws-chat-user')).toHaveCount(0);
 await page.locator('[data-ws-action=file][data-value=team-review]').click();await page.locator('[data-md-action=ask]').click();await expect(page.locator('#md-agent-host .agent-new-task')).toBeVisible();await page.locator('#md-agent-host .agent-new-task').click();await expect(page.locator('#md-agent-host #ws-composer-hint')).toContainText('当前会议');await expect(page.locator('#md-agent-host textarea')).toHaveValue('');
});
test('personal home history and meeting Agents can start fresh without removing history',async({page})=>{
 await page.goto(url);await page.locator('#history-task-list .history-row').first().click();const input=page.locator('#xiaozhi-input');await input.fill('保留的历史问题');await input.press('Enter');await expect(page.locator('#agent-history-messages')).toContainText('保留的历史问题');
 await page.locator('#xiaozhi-new-task').click();await expect(page.locator('#agent-history-session')).toBeHidden();await expect(input).toHaveValue('');await expect(input).toBeFocused();
 await page.locator('#history-task-list .history-row').first().click();await expect(page.locator('#agent-history-messages')).toContainText('保留的历史问题');await page.locator('#xiaozhi-collapse').click();await page.locator('#view-panorama').click();await page.locator('[data-md-action=ask]').click();await input.fill('会议独立问题');await input.press('Enter');await expect(page.locator('.md-agent-messages')).toContainText('会议独立问题');await page.locator('#xiaozhi-new-task').click();await expect(page.locator('.md-agent-messages article')).toHaveCount(0);await expect(page.locator('.md-agent-context')).toContainText('三季度产品复盘会议');await expect(input).toHaveValue('');
});
test('personal calendar and contacts reset only the Agent; a pending calendar draft is protected',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto(url);await page.locator('#todos-entry').click();await page.locator('#personal-actions [data-pa=agent]').click();const rail=page.locator('#pa-agent'),input=rail.locator('textarea');await input.fill('汇总今天安排');await input.press('Enter');await expect(rail.locator('.pa-message')).toHaveCount(1);await rail.getByRole('button',{name:'新建任务',exact:true}).click();await expect(rail.locator('.pa-message')).toHaveCount(0);await expect(input).toHaveValue('');
 if(process.env.PRD_CAPTURE)await page.screenshot({path:'src/prototype/prd/images/personal-calendar-agent.png'});
 await input.fill('明天 14:00 创建日程「新任务测试」');await input.press('Enter');await expect(rail.locator('#pa-agent-form')).toBeVisible();await rail.getByRole('button',{name:'新建任务',exact:true}).click();await expect(page.locator('.pa-dialog')).toContainText('保留这次修改');await page.locator('.pa-dialog [data-pa=modal-cancel]').last().click();await expect(rail.locator('#pa-agent-form')).toBeVisible();await rail.getByRole('button',{name:'新建任务',exact:true}).click();await page.locator('[data-pa=discard]').click();await expect(rail.locator('#pa-agent-form')).toHaveCount(0);
 await page.locator('[data-contacts-entry]').click();await page.locator('.contacts-xiaozhi-entry').click();const contact=page.locator('#contacts-xiaozhi-rail');await contact.locator('textarea').fill('本次联系人的新问题');await contact.locator('textarea').press('Enter');await contact.getByRole('button',{name:'新建任务',exact:true}).click();await expect(contact.locator('textarea')).toHaveValue('');await expect(contact.locator('textarea')).toBeFocused();
 for(const width of [1440,390]){await page.setViewportSize({width,height:844});await expect(contact.getByRole('button',{name:'新建任务',exact:true})).toBeInViewport({ratio:1});}
});
test('recording new task isolates delayed replies without stopping recording',async({page})=>{
 await page.goto(url);await page.locator('#start-recording').click();await page.getByRole('button',{name:'开始授权',exact:true}).click();await page.locator('#recording-assistant-toggle').click();await page.locator('#recording-assistant-input').fill('上一任务的问题');await page.locator('#recording-assistant-send').click();await page.locator('#recording-assistant-new-task').click();await expect(page.locator('#recording-assistant-messages')).not.toContainText('上一任务的问题');await expect(page.locator('#recording-assistant-messages')).toContainText('开始新的任务');await expect(page.locator('#recording-live-state')).toContainText('录音中');
 await page.waitForTimeout(650);await expect(page.locator('.recording-chat-row')).toHaveCount(0);await page.locator('#recording-assistant-input').fill('新的提问');await page.locator('#recording-assistant-send').click();await expect(page.locator('.recording-chat-row.assistant')).toHaveCount(1);
});
