import { expect, test, type Page } from "@playwright/test";
import M from "../../src/features/spaces/model/core";
import type { WorkspaceState } from "../../src/features/spaces/model/types";
const go = (page: Page, view: string, space = "personal", actor = "zhang") => page.goto(`/workbench/?view=${view}&space=${space}&actor=${actor}`);
const raw = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem("eureka:workspaces:v2")!) as WorkspaceState);
async function seed(page: Page) {
  const s = M.seed();
  M.consumeMinutes(M.get(s, "personal"), "previous-personal-recording", 12);
  const second = M.create(s, { orderId: "second-ui", name: "设计项目工作区", country: "中国", cycle: "month", seats: 3 });
  second.members.push({ id: "lin", name: "林晓", email: "lin.xiao@eureka.example", role: "member", status: "active", joined: "2026-10-09" });
  await page.addInitScript(s => { if (!sessionStorage.getItem("multi-seed")) { localStorage.setItem("eureka:workspaces:v2", JSON.stringify(s)); sessionStorage.setItem("multi-seed", "1"); } }, s);
  return second.id;
}
test("account joins a second team, switches all workspaces and can still create another", async ({ page }) => {
  await go(page, "invitations");
  await page.getByRole("button", { name: "接受并进入" }).click();
  await expect(page.getByRole("region", { name: "团队简报", exact: true })).toBeVisible();
  const s = await raw(page), second = M.accountTeams(s).find(w => w.id !== "team-eureka")!;
  expect(M.accountTeams(s)).toHaveLength(2);
  await page.locator("#ws-switcher").click();
  await expect(page.locator("#ws-menu")).toContainText("增长研究小组");
  await expect(page.locator("#ws-menu")).toContainText("EurekaMind 产品团队");
  await expect(page.locator("#ws-menu")).not.toContainText("冻结");
  await page.screenshot({ path: "test-results/multi-workspace-menu.png" });
  await page.locator("#ws-menu").getByRole("button", { name: /EurekaMind 产品团队/ }).click();
  await expect(page).toHaveURL(/space=team-eureka/);
  await go(page, "home", second.id);
  await expect(page.locator(".team-overview-head")).toBeVisible();
  await go(page, "create-team");
  await expect(page.locator("#ws-dialog")).toContainText("Unlimited");
  await expect(page.locator("#ws-dialog")).not.toContainText("无法创建团队");
});
test("personal subscription shows the current plan and remains usable across team switches", async ({ page }) => {
  const second = await seed(page);
  await go(page, "subscription");
  await expect(page.locator("#ws-view")).not.toContainText("冻结");
  await expect(page.locator('[data-ws-action="personal-buy"]')).toBeEnabled();
  for (const [width, height] of [[1440, 900], [1080, 680]]) {
    await page.setViewportSize({ width, height });
    await page.screenshot({ path: `test-results/personal-subscription-${width}.png`, animations: "disabled" });
  }
  await page.locator('[data-ws-action="personal-buy"]').click();
  await expect(page.locator("#ws-dialog")).toBeVisible();
  await go(page, "recording");
  await expect(page.getByRole("button", { name: "结束录音", exact: true })).toBeVisible();
  const before = await raw(page);
  await page.getByRole("button", { name: "结束录音", exact: true }).click();
  await expect(page.getByText("录音已结束，转写内容已保存", { exact: true })).toBeVisible();
  const after = await raw(page);
  const used = M.get(after, "personal").transcriptionUsage!.used;
  expect(used).toBe(12);
  expect(M.get(after, second).credits).toEqual(M.get(before, second).credits);
  expect(M.get(after, second).transcriptionUsage).toEqual(M.get(before, second).transcriptionUsage);
  await go(page, "subscription", second);
  await expect(page.locator("#ws-view")).toContainText("管理员为本工作区统一付款");
  await go(page, "subscription");
  await expect(page.locator(".ps-account progress")).toHaveAttribute("value", String(400 - used));
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test("recording and Agent consume only their originating workspace, switch and reload preserve usage", async ({ page }) => {
  const second = await seed(page);
  await go(page, "recording", second);
  const before = await raw(page);
  await page.getByRole("button", { name: "结束录音", exact: true }).click();
  await expect(page.getByText("录音已结束，转写内容已保存", { exact: true })).toBeVisible();
  let s = await raw(page);
  expect(M.get(s, second).transcriptionUsage?.used).toBeGreaterThan(0);
  expect(M.get(s, "team-eureka").credits).toEqual(M.get(before, "team-eureka").credits);
  expect(M.get(s, "personal").credits).toEqual(M.get(before, "personal").credits);
  await go(page, "home", second);
  await page.getByRole("button", { name: "Ask Agent", exact: true }).click();
  await page.getByLabel("向团队 Agent 提问").fill("总结当前会议");
  await page.getByRole("button", { name: "发送问题", exact: true }).click();
  await expect.poll(async () => M.get(await raw(page), second).credits.used).toBeGreaterThan(0);
  s = await raw(page);
  expect(M.get(s, "team-eureka").credits).toEqual(M.get(before, "team-eureka").credits);
  expect(M.get(s, "personal").credits).toEqual(M.get(before, "personal").credits);
  await go(page, "subscription", "team-eureka");
  await go(page, "subscription", second);
  await expect(page.locator("#ws-view")).toContainText(`本工作区累计转写：${M.get(s, second).transcriptionUsage?.used} 分钟`);
});
test("per-team sharing switches and membership removal remain isolated", async ({ page }) => {
  const second = await seed(page);
  await go(page, "content-permissions", second);
  await page.getByRole("switch", { name: "会议信息共享给团队" }).click();
  await page.getByRole("checkbox", { name: /林晓/ }).check();
  await page.getByRole("button", { name: "保存授权" }).click();
  await go(page, "content-permissions", "team-eureka");
  await expect(page.getByRole("switch", { name: "会议信息共享给团队" })).not.toBeChecked();
  await go(page, "members", "team-eureka", "lin");
  await page.locator('[data-ws-action="member-remove"][data-value="zhang"]').click();
  await page.locator("#ws-dialog").getByRole("button", { name: "确认", exact: true }).click();
  await go(page, "content-permissions", second);
  await expect(page.getByRole("switch", { name: "会议信息共享给团队" })).toBeChecked();
  await go(page, "subscription");
  await expect(page.locator("#ws-view")).not.toContainText("冻结");
  expect(M.accountTeams(await raw(page))).toHaveLength(1);
});
