import { expect, test } from "@playwright/test";
import M from "../../src/features/spaces/model/core";
const rebind = (s: ReturnType<typeof M.seed>, wid: string) => { M.unbind(s, "dev-personal"); M.bind(s, "dev-personal", wid); };
import PS from "../../src/features/spaces/model/subscription";
import { createWorkspaceStore } from "../../src/features/spaces/model/store";
const draft = (orderId: string) => ({ orderId, name: `工作区 ${orderId}`, country: "中国", cycle: "month" as const, seats: 3 });
test("multiple teams preserve settings, memberships and billing, with idempotent creation and invitations", () => {
  const s = M.seed(), first = M.get(s, "team-eureka"), before = structuredClone(first);
  const second = M.create(s, draft("second"));
  const third = M.acceptInvite(s, "invite-growth");
  expect(M.accountTeams(s)).toHaveLength(3);
  expect(first).toEqual(before);
  expect(M.create(s, draft("second")).id).toBe(second.id);
  expect(M.accountTeams(s)).toHaveLength(3);
  expect(() => M.acceptInvite(s, "invite-growth")).toThrow();
  expect(() => M.create(s, draft(""))).toThrow();
  s.invitations.push({ id: "duplicate", workspaceId: third.id, teamName: third.name, status: "pending", role: "member" });
  expect(() => M.acceptInvite(s, "duplicate")).toThrow("不能重复加入");
  expect(s.invitations.at(-1)?.status).toBe("pending");
});
test("members consume one workspace's credits and transcription, never a personal or second team pool", () => {
  const s = M.seed(), a = M.get(s, "team-eureka"), b = M.create(s, draft("second")), personal = M.get(s, "personal");
  const original = structuredClone([b.credits, personal.credits]);
  M.settleCredits(a, "usage-a", "本区任务", { inputTokens: 100, outputTokens: 200 });
  M.consumeMinutes(a, "record-a", 12);
  M.consumeMinutes(a, "record-a", 12);
  expect(a.transcriptionUsage?.used).toBe(12);
  expect([b.credits, personal.credits]).toEqual(original);
  M.consumeMinutes(b, "record-a", 7);
  expect(b.transcriptionUsage?.used).toBe(7);
  a.credits.used = a.credits.total;
  expect(() => M.settleCredits(a, "exhausted", "无法执行", { inputTokens: 10, outputTokens: 10 })).toThrow("Credits 不足");
  expect([b.credits, personal.credits]).toEqual(original);
  a.status = "expired";
  expect(() => M.consumeMinutes(a, "expired", 1)).toThrow("只读");
  expect(() => M.settleCredits(personal, "personal", "冻结", { inputTokens: 1, outputTokens: 1 })).toThrow("冻结");
  expect(() => M.consumeMinutes(personal, "personal", 1)).toThrow("冻结");
});
test("personal subscription clock and balances freeze once, additional memberships do not restart freezing", () => {
  const s = M.seed(new Date("2026-10-01T00:00:00Z")), p = M.get(s, "personal"), a = M.get(s, "team-eureka");
  delete p.entitlementFreeze;
  p.personalSubscription = { plan: "Pro", minutes: 99999, credits: 5000, renew: true, cycle: "month", endsAt: "2026-11-01T00:00:00.000Z", nextRefresh: "2026-11-01T00:00:00.000Z" };
  M.reconcileEntitlements(s, new Date("2026-10-01T00:00:00Z"));
  const b = M.create(s, draft("second"));
  expect(M.get(s, "personal").entitlementFreeze?.since).toBe("2026-10-01T00:00:00.000Z");
  expect(PS.current(p, "2027-01-01T00:00:00Z").plan).toBe("Pro");
  expect(PS.current(p).remainingDays).toBe(31);
  expect(() => PS.create(p, "year")).toThrow("冻结");
  const credits = structuredClone(p.credits);
  a.members.find(m => m.id === "zhang")!.status = "removed";
  M.reconcileEntitlements(s, new Date("2026-10-11T00:00:00Z"));
  expect(M.get(s, "personal").entitlementFreeze?.teamIds).toEqual([b.id]);
  b.members.find(m => m.id === "zhang")!.status = "removed";
  M.reconcileEntitlements(s, new Date("2026-10-21T00:00:00Z"));
  expect(p.entitlementFreeze).toBeUndefined();
  expect(p.personalSubscription.endsAt).toBe("2026-11-21T00:00:00.000Z");
  M.reconcileEntitlements(s, new Date("2026-10-22T00:00:00Z"));
  expect(p.personalSubscription.endsAt).toBe("2026-11-21T00:00:00.000Z");
  expect(p.credits).toEqual(credits);
});
test("removal from one team leaves all other memberships, sharing policies, content and entitlements intact", () => {
  const s = M.seed(), a = M.get(s, "team-eureka"), b = M.acceptInvite(s, "invite-growth");
  M.setDeviceSharing(s, a.id, "zhang", "meetings", true, ["lin"]);
  M.setDeviceSharing(s, b.id, "zhang", "meetings", true, ["wang"]);
  rebind(s, b.id);
  const recorded = M.sync(s, "dev-personal");
  expect(recorded.space.id).toBe(b.id);
  expect(recorded.sharedTeams?.map(w => w.id)).toEqual([b.id]);
  expect(a.files.some(f => f.sourceFileId === recorded.file.id)).toBe(false);
  const before = structuredClone(b);
  M.memberAction(s, a, "zhang", "remove", undefined, "lin");
  expect(b).toEqual(before);
  expect(M.accountTeams(s).map(w => w.id)).toEqual([b.id]);
  expect(M.get(s, "personal").entitlementFreeze).toBeTruthy();
  expect(M.capturePreferences(s).teams[a.id]).toBeUndefined();
  expect(M.capturePreferences(s).teams[b.id].meetings?.enabled).toBe(true);
  expect(s.devices[0].bound).toBe(true);
});
test("frozen personal device captures remain raw while selected team captures consume only their own pool", () => {
  const s = M.seed(), p = M.get(s, "personal"), a = M.get(s, "team-eureka");
  expect(M.sync(s, "dev-personal").file.status).toBe("原始音频 · 待处理");
  expect(p.transcriptionUsage).toBeUndefined();
  rebind(s, a.id);
  const first = M.sync(s, "dev-personal", "zhang", { sourceId: "once" });
  M.sync(s, "dev-personal", "zhang", { sourceId: "once" });
  expect(first.file.shared).toEqual([]);
  expect(a.transcriptionUsage?.used).toBe(12);
  expect(p.transcriptionUsage).toBeUndefined();
});
test("failed writes cannot partially join a workspace or change frozen entitlement snapshots", () => {
  const data = new Map<string, string>(); data.set(M.KEY, JSON.stringify(M.seed()));
  const storage = { getItem: (key: string) => data.get(key) || null, setItem: () => { throw Error("quota"); } } as unknown as Storage;
  const repo = createWorkspaceStore(storage), before = repo.read();
  expect(() => repo.change(s => M.acceptInvite(s, "invite-growth"))).toThrow("保存失败");
  expect(repo.read()).toEqual(before);
});
