import {test,expect,Page} from '@playwright/test';
test.use({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai'});
const url='/prototype/one-to-one-reference/team-only-app.html?edition=personal&personal=1';
const action=(p:Page,n:string)=>p.locator(`[data-ws-action="${n}"]`).filter({visible:true}).first();
const settings=async(p:Page)=>{await p.locator('#user-card').click();await p.locator('#ws-menu [data-ws-action=settings]').click();};
const billing=async(p:Page)=>{await p.locator('#user-card').click();await p.locator('#ws-menu [data-ws-action=page][data-value=billing]').click();};
const submit=(p:Page)=>p.locator('#ws-dialog button[type=submit]').click();
const snapshot=(p:Page)=>p.evaluate(()=>JSON.parse(localStorage.getItem('eureka:workspaces:v2')!));
const capture=async(p:Page,name:string)=>{if(process.env.PRD_CAPTURE){await expect(p.locator('#ws-toast')).toBeHidden();await expect(p.locator('#toast')).not.toHaveClass(/show/);await p.screenshot({path:`src/prototype/prd/images/${name}.png`});}};
test('calendar day/week/month share records, creation and edits; agent is responsive and creates todos',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.locator('#todos-entry').click();
  await expect(page.locator('#todos-entry')).toContainText('日程与待办');await expect(page.locator('#pa-search,[data-pa=filter]')).toHaveCount(0);await expect(page.locator('.pa-day-section')).toHaveCount(2);
  await expect(page.locator('#pa-list [data-personal-open=calendar-meeting-review]')).toContainText('09:30');await expect(page.locator('#pa-list [data-personal-open=calendar-todo-demo]')).toContainText('09:30');
  await capture(page,'personal-calendar-day');
  await page.locator('[data-pa=calendar-mode][data-id=week]').click();await expect(page.locator('.pa-calendar-cell')).toHaveCount(7);await capture(page,'personal-calendar-week');
  await page.locator('[data-pa=calendar-mode][data-id=month]').click();await expect(page.locator('.pa-calendar-cell')).toHaveCount(42);await capture(page,'personal-calendar-month');
  await page.locator('#personal-actions [data-pa=new-schedule]').click();await expect(page.locator('.pa-create-dialog')).toBeVisible();await page.locator('[name=title]').fill('跨日研发讨论');await capture(page,'personal-create-schedule');await page.locator('[name=start]').fill('2026-10-24T23:30');await page.locator('[name=end]').fill('2026-10-25T00:30');await page.locator('#pa-edit-form button[type=submit]').click();
  await page.locator('[data-pa=calendar-mode][data-id=day]').click();await expect(page.locator('#pa-list')).toContainText('跨日研发讨论');await page.locator('#pa-calendar-date').fill('2026-10-25');await expect(page.locator('#pa-list')).toContainText('跨日研发讨论');
  await page.locator('.pa-list-row').filter({hasText:'跨日研发讨论'}).click();await page.locator('[data-pa=edit]').click();await page.locator('[name=title]').fill('跨日研发讨论 · 更新');await page.locator('#pa-edit-form button[type=submit]').click();await page.locator('[data-pa=back]').click();
  await page.locator('#personal-actions [data-pa=new-todo]').click();await page.locator('[name=title]').fill('核对交付资料');await page.locator('#pa-edit-form button[type=submit]').click();
  await page.locator('#personal-actions [data-pa=agent]').click();await page.locator('[data-pa=agent-summary]').click();await expect(page.locator('#pa-agent-result')).toContainText('核对交付资料');
  await page.locator('#pa-prompt').fill('明天 18:00 创建待办「汇总评审结论」');await page.locator('#pa-prompt').press('Enter');await expect(page.locator('#pa-agent-form [name=end]')).toHaveCount(0);await page.locator('#pa-agent-form button[type=submit]').click();await page.locator('#pa-agent [data-pa=open-created]').click();await expect(page.locator('.pa-origin')).toContainText('Agent 创建');
  await page.locator('[data-pa=edit]').click();await page.locator('[name=notes]').fill('从 Agent 创建后手动补充');await page.locator('#pa-edit-form button[type=submit]').click();await page.locator('[data-pa=back]').click();await page.locator('#personal-actions [data-pa=agent]').click();
  const rail=page.locator('#pa-agent'),handle=rail.getByRole('separator');await expect(rail).toBeInViewport();await expect(page.locator('#pa-prompt')).toBeInViewport();const panelBox=(await rail.boundingBox())!,contentBox=(await page.locator('.pa-content').boundingBox())!;expect(panelBox.x).toBeGreaterThanOrEqual(contentBox.x+contentBox.width);expect(Math.abs(panelBox.y-contentBox.y)).toBeLessThan(3);const before=panelBox.width;await handle.focus();await handle.press('ArrowLeft');expect((await rail.boundingBox())!.width).toBeGreaterThan(before);await page.locator('#pa-prompt').focus();expect(await page.locator('#pa-prompt').evaluate(el=>getComputedStyle(el).boxShadow)).toBe('none');expect(await page.locator('#pa-prompt').evaluate(el=>getComputedStyle(el).outlineWidth)).toBe('0px');await capture(page,'personal-calendar-agent');await page.locator('#pa-prompt').fill('这周的日程有哪些？');await handle.focus();await handle.press('End');expect(await page.locator('#personal-actions').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThan(3);await handle.press('Home');await expect(page.locator('#pa-prompt')).toHaveValue('这周的日程有哪些？');
  for(const width of [1280,1024,390]){await page.setViewportSize({width,height:900});const b=(await rail.boundingBox())!;expect(b.x).toBeGreaterThanOrEqual(0);expect(b.x+b.width).toBeLessThanOrEqual(width+1);await page.locator('#pa-prompt').scrollIntoViewIfNeeded();await expect(page.locator('#pa-prompt')).toBeInViewport();}
  await page.setViewportSize({width:1440,height:1000});await page.reload();await page.locator('#todos-entry').click();await page.locator('#pa-calendar-date').fill('2026-10-24');await expect(page.locator('#pa-list')).toContainText('跨日研发讨论 · 更新');expect(errors).toEqual([]);
});
test('personal USD subscription pays after retry, persists, restores once and leaves Team unchanged',async({page})=>{
  await page.goto(url);await billing(page);await expect(page.locator('.ps-account')).toContainText('标准版');await expect(page.locator('.ps-account')).toContainText('400');await expect(page.locator('.ps-plans')).toContainText('$17.99');await expect(page.locator('.ps-plans')).toContainText('$99.99');await capture(page,'personal-subscription');
  await page.locator('[data-ws-action=personal-cycle][data-value=month]').click();await action(page,'personal-buy').click();const before=await snapshot(page);await expect(page.locator('#ws-dialog')).toContainText('$17.99 USD');await capture(page,'personal-subscription-checkout');await action(page,'personal-fail').click();await expect(page.locator('#ws-dialog')).toContainText('未开通权益');
  await page.reload();await billing(page);await action(page,'personal-checkout').click();await page.locator('#ws-dialog [name=method]').selectOption('Apple Pay（模拟）');await submit(page);await expect(page.locator('#ws-dialog')).toContainText('Pro 已生效');await capture(page,'personal-subscription-success');
  await action(page,'close-dialog').click();await expect(page.locator('.ps-account')).toContainText('99,999');let after=await snapshot(page);const personal=after.spaces.find((w:{id:string})=>w.id==='personal');expect(personal.credits.total).toBe(before.spaces.find((w:{id:string})=>w.id==='personal').credits.total+5000);expect(after.spaces.filter((w:{type:string})=>w.type==='team')).toEqual(before.spaces.filter((w:{type:string})=>w.type==='team'));
  const download=page.waitForEvent('download');await action(page,'personal-receipt').click();expect((await download).suggestedFilename()).toMatch(/INV-PERSONAL.*txt/);
  await action(page,'personal-renew').click();await action(page,'confirm').click();await expect(page.locator('.ps-account')).toContainText('权益保留至');await action(page,'personal-restore').click();after=await snapshot(page);expect(after.spaces.find((w:{id:string})=>w.id==='personal').credits.total).toBe(personal.credits.total);
  await page.locator('[data-ws-action=personal-cycle][data-value=year]').click();await action(page,'personal-buy').click();await expect(page.locator('#ws-dialog')).toContainText('$99.99 USD');await page.locator('#ws-dialog [data-ws-action=personal-cancel]').click();await action(page,'confirm').click();await expect(page.locator('#ws-view')).toContainText('已取消');
  await settings(page);await expect(page.locator('#personal-settings')).not.toContainText('日程与待办提醒');await expect(page.locator('.settings-profile')).toContainText('Pro');await expect(page.locator('.settings-usage')).toContainText('99,999');
});
test('personal payment failure to persist cannot activate subscription; calendar views fit small screens',async({page})=>{
  await page.goto(url);await billing(page);await action(page,'personal-buy').click();await page.evaluate(()=>{const orig=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='eureka:workspaces:v2')throw Error('quota');orig.call(this,k,v);};});await submit(page);await expect(page.locator('#ws-dialog .ws-form-error')).toContainText('存储空间不足');expect((await snapshot(page)).spaces.find((w:{id:string})=>w.id==='personal').personalSubscription).toBeUndefined();
  await page.reload();await page.locator('#todos-entry').click();for(const mode of ['day','week','month']){await page.locator(`[data-pa=calendar-mode][data-id=${mode}]`).click();await page.setViewportSize({width:390,height:844});expect(await page.locator('#personal-actions').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThan(3);}
});

test('creation modal keeps the calendar and protects unsaved input',async({page})=>{
  await page.goto(url);await page.locator('#todos-entry').click();
  const left=await page.locator('#home-entry .nav-label').boundingBox(),todo=await page.locator('#todos-entry .nav-label').boundingBox();expect(Math.abs(left!.x-todo!.x)).toBeLessThan(1);
  await page.locator('#personal-actions [data-pa=new-todo]').click();await expect(page.locator('#pa-list')).toBeVisible();await page.locator('#pa-edit-form [name=title]').fill('尚未保存');await page.keyboard.press('Escape');await expect(page.locator('.pa-dialog')).toBeVisible();await page.locator('.pa-dialog [data-pa=modal-cancel]').last().click();await expect(page.locator('#pa-edit-form [name=title]')).toHaveValue('尚未保存');await page.keyboard.press('Escape');await page.locator('[data-pa=discard]').click();await expect(page.locator('.pa-create-dialog')).toBeHidden();await expect(page.locator('#pa-list')).not.toContainText('尚未保存');
  await page.locator('#personal-actions [data-pa=new-schedule]').click();await page.setViewportSize({width:390,height:844});expect(await page.locator('.pa-create-dialog').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThan(3);await page.locator('#pa-edit-form button[type=submit]').scrollIntoViewIfNeeded();await expect(page.locator('#pa-edit-form button[type=submit]')).toBeInViewport();await page.keyboard.press('Escape');await expect(page.locator('.pa-create-dialog')).toBeHidden();
});
