import { expect, test } from '@playwright/test';
test.use({ channel: process.env.PLAYWRIGHT_CHANNEL || undefined, timezoneId:'Asia/Shanghai' });
const url='/prototype/one-to-one-reference/team-only-app.html?edition=personal&personal=1';
test('manual schedule, editing, reminder, notes and associated meeting persist in archives',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);
  await expect(page.locator('#todos-entry')).toBeVisible();
  await page.locator('[data-widget-all]').click();
  await page.locator('#thought-toolbar [data-th=calendar]').click();await page.locator('#personal-actions [data-pa=new-schedule]').click();
  await page.locator('#pa-edit-form [name=title]').fill('客户联调讨论');
  await page.locator('#pa-edit-form [name=start]').fill('2026-10-24T14:00');
  await page.locator('#pa-edit-form [name=end]').fill('2026-10-24T13:00');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  await expect(page.locator('[data-pa-error]:visible')).toContainText('结束时间');
  await page.locator('#pa-edit-form [name=end]').fill('2026-10-24T15:00');
  await page.locator('#pa-edit-form [name=location]').fill('会议室 A');
  await page.locator('#pa-edit-form [name=participants]').fill('张伟、Kevin');
  await page.locator('#pa-edit-form [name=reminder]').selectOption('30');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  await page.locator('.pa-list-row').filter({hasText:'客户联调讨论'}).click();
  await expect(page.locator('#personal-actions h1')).toHaveText('客户联调讨论');
  await expect(page.locator('.pa-detail-main')).toContainText('提前 30 分钟');
  await page.locator('[data-pa=notes]').click();
  await page.locator('dialog [name=notes]').fill('需要准备数据样本');
  await page.locator('dialog [data-pa=modal-confirm]').click();
  await page.locator('[data-pa=links]').click();
  await page.locator('dialog [name=linked]').first().check();
  await page.locator('dialog [data-pa=modal-confirm]').click();
  await expect(page.locator('.pa-linked')).toHaveCount(1);
  await page.locator('[data-pa=edit]').click();
  await page.locator('#pa-edit-form [name=title]').fill('客户联调讨论 · 更新');
  await page.locator('#home-entry').click();
  await expect(page.locator('.pa-dialog')).toBeVisible();
  await page.locator('dialog [data-pa=modal-confirm]').click();
  await page.locator('[data-widget-all]').click();
  await page.locator('#thought-file-search').fill('客户联调讨论');
  await page.locator('[data-thought-record]').click();
  await expect(page.locator('#personal-actions h1')).toHaveText('客户联调讨论 · 更新');
  await expect(page.locator('.pa-note')).toContainText('数据样本');
  await page.reload();
  await page.locator('[data-widget-all]').click();
  await page.locator('#thought-file-search').fill('客户联调讨论');
  await expect(page.locator('[data-thought-record]')).toContainText('手动创建');
  expect(errors).toEqual([]);
});
test('Agent creates one schedule with traceable source in the same archive',async({page})=>{
  await page.goto(url);await page.locator('[data-widget-all]').click();
  await page.locator('#thought-toolbar [data-th=calendar]').click();await page.locator('#personal-actions [data-pa=agent]').click();
  await page.locator('#pa-prompt').fill('帮我安排「团队复盘」');
  await page.locator('#pa-agent-prompt button[type=submit]').click();
  await expect(page.locator('#pa-agent-result')).toContainText('还需要具体日期');
  await expect(page.locator('#pa-agent-form [name=start]')).toHaveValue('');
  await page.locator('#pa-agent-form [name=start]').fill('2026-10-25T14:00');
  await page.locator('#pa-agent-form [name=end]').fill('2026-10-25T15:00');
  await page.locator('#pa-agent-form button[type=submit]').click();
  await page.locator('[data-pa=open-created]').click();
  await expect(page.locator('#personal-actions h1')).toHaveText('团队复盘');
  await expect(page.locator('.pa-origin')).toContainText('Agent 创建');
  await page.locator('[data-pa=source-session]').click();
  await expect(page.locator('#pa-agent')).toContainText('帮我安排「团队复盘」');
  await page.locator('[data-pa=close-agent]').click();
  await page.locator('[data-pa=back]').click();
  await expect(page.locator('.pa-list-row').filter({hasText:'团队复盘'})).toHaveCount(1);
});
test('To-dos details toggle, notes, original capture and Settings independent page',async({page})=>{
  await page.goto(url);await page.locator('#todos-entry').click();
  await page.locator('[data-personal-open="calendar-todo-demo"]').click();
  await expect(page.locator('.pa-origin audio')).toHaveCount(1);
  await page.locator('[data-pa=edit]').click();await page.locator('[name=notes]').fill('周五前发给 Kevin');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  await page.locator('[data-pa=toggle]').click();await expect(page.locator('.pa-status')).toHaveText('已完成');
  await page.locator('[data-pa=toggle]').click();await expect(page.locator('.pa-status')).toHaveText('待完成');
  await page.locator('#user-card').click();await page.locator('#ws-menu [data-ws-action=settings]').click();
  await expect(page.locator('#personal-settings')).toBeVisible();await expect(page.locator('#user-menu')).not.toBeVisible();
  await expect(page.locator('#personal-settings')).not.toContainText('日程与待办提醒');await page.locator('[data-settings-language=asr]').selectOption('zh-Hans');
  await page.locator('[data-settings-close]').click();await page.locator('#todos-entry').click();await page.locator('[data-personal-open="calendar-todo-demo"]').click();
  await expect(page.locator('.pa-note')).toContainText('周五');await expect(page.locator('.pa-notice')).toContainText('不会发送');
  await page.locator('#user-card').click();await page.locator('#ws-menu [data-ws-action=settings]').click();await expect(page.locator('#ws-menu')).not.toBeVisible();await expect(page.locator('#personal-settings')).toBeVisible();await expect(page.locator('[data-settings-language=asr]')).toHaveValue('zh-Hans');
});
test('schedule recording is linked once; personal navigation is hidden in Team',async({page})=>{
  await page.goto(url);await page.locator('[data-today-asset="schedule-1"]').first().click();
  const before=await page.locator('.pa-linked').count();
  await page.locator('[data-pa=record]').click();await page.locator('#recording-finish').click();
  await expect(page.locator('#personal-actions')).toBeVisible();
  await expect(page.locator('.pa-linked')).toHaveCount(before+1);
  await page.locator('.pa-linked').last().click();
  await expect(page.locator('#meeting-detail-root')).toBeVisible();
  await expect(page.locator('#meeting-detail-root')).toContainText('产品方案评审 · 会议录音');
  await page.locator('#home-entry').click();await expect(page.locator('#meeting-list .home-meeting-row').filter({hasText:'产品方案评审 · 会议录音'})).toBeVisible();
  await page.reload();await expect(page.locator('#meeting-list .home-meeting-row').filter({hasText:'产品方案评审 · 会议录音'})).toBeVisible();
  await page.locator('#ws-switcher').click();await page.locator('#ws-menu [data-ws-action=switch]').nth(1).click();
  await expect(page.locator('#todos-entry')).not.toBeVisible();await expect(page.locator('#personal-actions')).not.toBeVisible();
});
test('detail, To-dos, Agent and Settings screenshots and responsive layout',async({page})=>{
  await page.setViewportSize({width:1440,height:1000});await page.goto(url);
  await page.locator('[data-today-asset="schedule-1"]').first().click();
  if(process.env.PRD_CAPTURE)await page.screenshot({path:'src/prototype/prd/images/personal-schedule.png'});
  await page.locator('#todos-entry').click();await page.locator('[data-personal-open="calendar-todo-demo"]').click();
  if(process.env.PRD_CAPTURE)await page.screenshot({path:'src/prototype/prd/images/personal-todo.png'});
  await page.locator('#user-card').click();await page.locator('#ws-menu [data-ws-action=settings]').click();
  if(process.env.PRD_CAPTURE)await page.screenshot({path:'src/prototype/prd/images/personal-settings.png'});
  await page.locator('[data-settings-close]').click();await page.locator('[data-widget-all]').click();await page.locator('#thought-toolbar [data-th=calendar]').click();await page.locator('#personal-actions [data-pa=agent]').click();
  await page.locator('#pa-prompt').fill('2026-10-24 14:00–15:00，安排「产品方案讨论」');await page.locator('#pa-agent-prompt button[type=submit]').click();
  if(process.env.PRD_CAPTURE)await page.screenshot({path:'src/prototype/prd/images/personal-schedule-agent.png'});
  for(const width of [1440,1280,1024,390]){await page.setViewportSize({width,height:1000});const bounds=await page.locator('#pa-agent').boundingBox();expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(width+1);}
});
