import {test,expect} from '@playwright/test';
test.use({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai'});
test('capture functional PRD illustrations from the running prototype',async({page})=>{
  test.skip(!process.env.PRD_ILLUSTRATIONS,'Run explicitly to refresh PRD interaction images');
  test.setTimeout(90000);
  const app='/prototype/one-to-one-reference/team-only-app.html?edition=personal&personal=1';
  const capture=async(name:string)=>{await page.screenshot({path:`src/prototype/prd/images/${name}.png`});};
  const action=(n:string,v?:string)=>page.locator(`[data-ws-action="${n}"]${v?`[data-value="${v}"]`:''}`).filter({visible:true}).first();
  await page.goto('/prototype/auth-shell.html');await capture('auth');
  await page.goto(app);await page.locator('#ws-switcher').click();await capture('workspace-menu');await page.locator('#ws-switcher').click();
  await page.locator('[data-widget-all]').click();await capture('thoughts');
  await page.locator('#thought-toolbar [data-pa=new-schedule]').click();
  await page.locator('#pa-edit-form [name=title]').fill('产品方案讨论');await page.locator('#pa-edit-form [name=start]').fill('2026-10-24T14:00');await page.locator('#pa-edit-form [name=end]').fill('2026-10-24T15:00');await page.locator('#pa-edit-form [name=participants]').fill('张伟、Kevin');await capture('schedule-edit');
  await page.locator('#pa-edit-form button[type=submit]').click();await page.locator('#home-entry').click();
  await page.locator('#meeting-date-filter-trigger').click();await capture('meeting-filter');await page.keyboard.press('Escape');
  await page.locator('#view-panorama').click();await page.locator('[data-md-action=edit]').click();await capture('meeting-edit');
  await page.locator('[data-md-action=exit-edit]').click();
  await page.locator('#home-entry').click();await page.locator('#recording-recycle-entry').click();await capture('recording-recycle');
  await page.locator('#start-recording').click();await page.locator('#permission-authorize').click();await expect(page.locator('#recording-layout')).toBeVisible();await capture('recording');await page.locator('#recording-abandon').click();
  await page.locator('#ws-switcher').click();await action('plan').click();await capture('team-plan');
  await action('setup').click();await page.locator('#ws-dialog [name=name]').fill('EurekaMind 业务团队');await page.locator('#ws-dialog button[type=submit]').click();await capture('team-checkout');await action('close-dialog').click();
  await page.locator('#ws-switcher').click();await action('switch','team-eureka').click();
  await page.locator('#ws-team-nav [data-value=members]').click();await capture('members');await action('invite').click();await page.locator('#ws-dialog [name=emails]').fill('alice@eureka.example');await capture('member-invite');await action('close-dialog').click();
  await page.locator('#ws-team-nav [data-value=devices]').click();await capture('devices');await action('register-device').click();await page.locator('#ws-dialog [name=serial]').fill('474204126010000027');await page.locator('#ws-dialog [name=model]').fill('W2');await capture('device-register');await action('close-dialog').click();
  await page.locator('#ws-team-nav [data-value=billing]').click();await action('page','credits').click();await capture('credits');await action('page','settings').click();await capture('team-settings');
});
