import {test,expect,Page} from '@playwright/test';
test.use({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,viewport:{width:1440,height:1000}});
const url='/prototype/one-to-one-reference/team-only-app.html?edition=personal&personal=1';
const action=(p:Page,n:string)=>p.locator(`[data-ws-action=${n}]`).filter({visible:true}).first();
const tab=(p:Page,n:string)=>p.locator(`.ws-tabs [data-value=${n}]`);
async function capture(p:Page,name:string){if(process.env.PRD_CAPTURE){await expect(p.locator('#ws-toast')).toBeHidden();await p.mouse.move(700,950);await p.screenshot({path:`src/prototype/prd/images/${name}.png`});}}
async function seats(p:Page){return p.evaluate(()=>JSON.parse(localStorage.getItem('eureka:workspaces:v2')!).spaces.find((s:{id:string})=>s.id==='team-eureka').seats);}
test.beforeEach(async({page})=>{await page.goto(url);await page.locator('#ws-switcher').click();await page.locator('#ws-menu [data-value=team-eureka]').click();await page.locator('#ws-team-nav [data-value=billing]').click();});
test('visible add-seats entry opens a positive quote and payment changes capacity only on success',async({page})=>{
 const add=page.locator('.ws-plan-current [data-ws-action=add-seats]');await expect(add).toBeInViewport();await expect(add).toHaveText('增加席位');await capture(page,'billing');await add.click();await expect(page.locator('#ws-dialog h2')).toHaveText('增加席位');await expect(page.locator('#ws-dialog [name=seats]')).toHaveValue('7');await expect(page.locator('#ws-dialog [name=seats]')).toHaveAttribute('min','7');await expect(page.locator('#ws-seat-estimate')).toContainText('¥1,908.00');await capture(page,'seat-add');await page.locator('#ws-dialog [name=seats]').fill('6');await page.locator('#ws-dialog button[type=submit]').click();await expect(page.locator('#ws-dialog h2')).toHaveText('增加席位');await page.locator('#ws-dialog [name=seats]').fill('7');await page.locator('#ws-dialog button[type=submit]').click();await expect(page.locator('#ws-dialog h2')).toHaveText('确认加席订单');expect(await seats(page)).toBe(6);await action(page,'seat-pay-fail').click();expect(await seats(page)).toBe(6);await page.locator('#ws-dialog button[type=submit]').click();expect(await seats(page)).toBe(7);await action(page,'close-dialog').click();await page.reload();await page.locator('#ws-team-nav [data-value=billing]').click();expect(await seats(page)).toBe(7);
});
test('Credits purchase sits under balance; workspace settings use full available width on desktop and mobile',async({page})=>{
 await tab(page,'credits').click();await expect(page.locator('.ws-page-head [data-ws-action=topup]')).toHaveCount(0);await expect(page.locator('.ws-credit-summary [data-ws-action=topup]')).toBeInViewport();await capture(page,'credits');await action(page,'topup').click();await expect(page.locator('.ws-credit-packs')).toBeVisible();await action(page,'close-dialog').click();await tab(page,'settings').click();await capture(page,'team-settings');
 for(const width of [1920,1440,1024,390]){await page.setViewportSize({width,height:1000});const cards=page.locator('.ws-settings-form');for(const card of await cards.all()){expect(await card.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBeTruthy();const box=(await card.boundingBox())!;const nav=(await page.locator('.ws-tabs').boundingBox())!;expect(Math.abs(box.x-nav.x)).toBeLessThan(2);expect(Math.abs(box.width-nav.width)).toBeLessThan(2);}expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);await page.locator('[data-ws-form=settings] [name=name]').fill('自适应空间设置');await page.locator('[data-ws-form=settings] button[type=submit]').click();await expect(page.locator('#ws-switcher')).toContainText('自适应空间设置');}
 await tab(page,'credits').click();await expect(page.locator('.ws-credit-summary [data-ws-action=topup]')).toBeVisible();await tab(page,'billing').click();await expect(page.locator('[data-ws-action=add-seats]')).toBeVisible();
});
