import { test, expect } from "@playwright/test";
import M from "../../src/features/spaces/model/core";
import { createWorkspaceStore } from "../../src/features/spaces/model/store";
import { createActions, createThoughts, createContacts, type Contact } from "../../src/features/personal/store";
import { ingestCustomer } from "../../src/features/personal/contact-identity";
const memory = () => { const values = new Map<string, string>(); return { getItem: (k: string) => values.get(k) ?? null, setItem: (k: string, v: string) => { values.set(k, v); }, removeItem: (k: string) => { values.delete(k); } } as Storage; };
const contact = (ownerId: string): Contact => ({ id: "c1", ownerId, name: "周宁", phone: "+8613800001001", company: "示例公司", role: "采购", summary: "示例", initials: "周", email: "", tag: "", count: 0, recent: "", region: "上海", subjectType: "person", createdAt: "2026-10-10", themes: [], memories: [], inferences: [], sharedWith: [] });
const init = () => { const storage = memory(), s = M.enrich(M.seed()), w = M.get(s, "team-eureka"); w.members.find(m => m.id === "lin")!.role = "member"; storage.setItem(M.KEY, JSON.stringify(s)); return { storage, s, w }; };
const now = () => new Date("2026-10-10T10:00:00+08:00");
test.describe("single-item permissions and team lifecycle", () => {
  test.beforeEach(() => Object.defineProperty(globalThis, "window", { configurable: true, value: { dispatchEvent() {} } }));
  test.afterEach(() => Reflect.deleteProperty(globalThis, "window"));
  test("members receive only item-level read access; admins manage all content", () => {
    const { s, w } = init(), a = M.addFile(w, { title: "A" }, "lin"), b = M.addFile(w, { title: "B" }, "lin");
    expect(M.getFile(w, a.id).id).toBe(a.id);
    M.share(w, a.id, ["kevin"], "lin");
    expect(M.getFile(w, a.id, "kevin").id).toBe(a.id);
    expect(() => M.getFile(w, b.id, "kevin")).toThrow();
    expect(() => M.edit(w, a.id, { title: "forbidden" }, "kevin")).toThrow(/编辑/);
    expect(() => M.share(w, a.id, ["kevin"], "lin", ["kevin"])).toThrow(/只读/);
    M.edit(w, a.id, { title: "admin edit" });
    expect(() => M.share(w, a.id, [])).toThrow(/仅所有者本人/);
    M.share(w, a.id, [], "lin");
    expect(() => M.getFile(w, a.id, "kevin")).toThrow();
    expect(M.getFile(w, a.id).title).toBe("admin edit");
    M.trash(w, a.id); M.trash(w, a.id, true); M.trash(w, a.id); M.purge(w, a.id);
    expect(w.files.some(f => f.id === a.id)).toBe(false);
    expect(() => M.setDeviceSharing(s, w.id, "lin", "meetings", true, ["kevin"], "lin")).toThrow(/单条/);
  });
  test("contact sharing is per record, revoked immediately; admin can edit another owner", () => {
    const { storage, w } = init();
    createContacts(storage, "lin", w.id).change(a => a.personal.contacts.push(contact("lin"), { ...contact("lin"), id: "c2" }));
    const viewer = createContacts(storage, "kevin", w.id);
    expect(viewer.readVisible().personal.contacts).toHaveLength(0);
    createContacts(storage, "lin", w.id).change(a => { a.personal.contacts[0].sharedWith = ["kevin"]; });
    expect(viewer.readVisible().personal.contacts.map(c => c.id)).toEqual(["c1"]);
    expect(() => createContacts(storage, "kevin", w.id, "lin").change(a => { a.personal.contacts[0].name = "bad"; })).toThrow(/管理员/);
    createContacts(storage, "zhang", w.id, "lin").change(a => { a.personal.contacts[0].name = "管理员维护"; });
    const before = storage.getItem("baizhi-v14-contacts");
    expect(() => createContacts(storage, "zhang", w.id, "lin").change(a => { a.personal.contacts[0].sharedWith = []; })).toThrow(/仅所有者本人/);
    expect(storage.getItem("baizhi-v14-contacts")).toBe(before);
    expect(() => createContacts(storage, "zhang", w.id, "lin").change(a => { a.personal.contacts[1].sharedWith = ["kevin"]; })).toThrow(/仅所有者本人/);
    expect(storage.getItem("baizhi-v14-contacts")).toBe(before);
    createContacts(storage, "lin", w.id).change(a => { a.personal.contacts[0].sharedWith = []; });
    expect(viewer.readVisible().personal.contacts).toHaveLength(0);
    expect(createContacts(storage, "zhang", w.id).readVisible().personal.contacts).toHaveLength(2);
  });
  test("admin reads and updates team thoughts, schedules, todos and ledger; member and personal isolation", () => {
    const { storage, w } = init();
    const action = createActions(storage, now, "lin", w.id).save({ id: "todo", type: "todo", title: "待办", start: "", end: "", reminder: "none", done: false, notes: "", location: "", participants: "", links: [], source: "manual", created: now().toISOString(), updated: now().toISOString() });
    createThoughts(storage, now, "lin", w.id).save({ id: "idea", type: "inspiration", title: "灵感", detail: "信息", date: "2026-10-10", time: "10:00", source: "manual" });
    createThoughts(storage, now, "lin", w.id).save({ id: "ledger", type: "ledger", title: "支出", detail: "交通", date: "2026-10-10", time: "10:00", source: "manual", amount: 20, currency: "CNY" });
    const adminActions = createActions(storage, now, "zhang", w.id);
    expect(adminActions.read().records.some(r => r.id === action.id)).toBe(true);
    adminActions.save({ ...adminActions.read().records[0], done: true });
    expect(createActions(storage, now, "lin", w.id).read().records[0].done).toBe(true);
    const adminThoughts = createThoughts(storage, now, "zhang", w.id), idea = adminThoughts.read().records.find(t => t.id === "idea")!;
    adminThoughts.save({ ...idea, title: "已更新" });
    expect(createThoughts(storage, now, "lin", w.id).read().records.find(t => t.id === "idea")?.title).toBe("已更新");
    expect(createThoughts(storage, now, "kevin", w.id).read().records).toHaveLength(0);
    expect(createThoughts(storage, now).read().records.some(t => t.id === "idea")).toBe(false);
    const repo = createWorkspaceStore(storage); repo.change(s => { M.get(s, w.id).members.find(m => m.id === "zhang")!.role = "member"; });
    expect(() => adminActions.save({ ...action, ownerId: "lin", done: false })).toThrow(/管理员/);
  });
  test("removal transfers all stores, unbinds and wipes only this team's devices; retry and personal data remain safe", () => {
    const { storage, w } = init();
    const core = createWorkspaceStore(storage);
    core.change(s => { M.addFile(M.get(s, w.id), { title: "待移交" }, "lin"); M.addThought(M.get(s, w.id), { title: "闪念", detail: "记录" }, "lin"); s.devices.find(d => d.id === "dev-team")!.localFiles = ["raw"]; });
    const binding = core.read().devices.find(d => d.id === "dev-team")!.bindings!.at(-1)!.id;
    createContacts(storage, "lin", w.id).change(a => a.personal.contacts.push(contact("lin")));
    storage.setItem("eureka:thoughts:team-eureka:lin:v1", JSON.stringify({ version: 1, records: [{ id: "local", type: "inspiration", title: "本地闪念" }] }));
    storage.setItem("eureka:actions:team-eureka:lin:v1", JSON.stringify({ version: 1, records: [{ id: "local-todo", type: "todo", title: "本地待办" }], meetings: [], sessions: [], settings: {} }));
    storage.setItem("eureka:thoughts:personal:lin:v1", "personal-safe");
    createWorkspaceStore(storage).change(s => M.memberAction(s, M.get(s, w.id), "lin", "remove"));
    const after = createWorkspaceStore(storage).read(), team = M.get(after, w.id), device = after.devices.find(d => d.id === "dev-team")!;
    expect(device.bound).toBe(false); expect(device.localFiles).toEqual([]); expect(device.wipeStatus).toBe("completed");
    expect(team.files.filter(f => f.title === "待移交")[0].owner).toBe("zhang");
    expect(team.thoughts![0].owner).toBe("zhang");
    expect(createContacts(storage, "zhang", w.id).readVisible().personal.contacts[0].previousOwnerId).toBe("lin");
    expect(createActions(storage, now, "zhang", w.id).read().records.some(r => r.id === "local-todo")).toBe(true);
    expect(createThoughts(storage, now, "zhang", w.id).read().records.some(r => r.id === "local")).toBe(true);
    expect(storage.getItem("eureka:thoughts:personal:lin:v1")).toBe("personal-safe");
    expect(after.devices[0].bound).toBe(true);
    expect(() => M.sync(after, "dev-team", "lin", { bindingId: binding, sourceId: "old" })).toThrow();
    M.invite(team, "lin.xiao@eureka.example"); M.memberAction(after, team, "lin", "accept");
    expect(() => M.sync(after, "dev-team", "lin", { bindingId: binding, sourceId: "old" })).toThrow();
    expect(() => createContacts(storage, "lin", w.id).readVisible()).toThrow(/权限/);
  });
  test("failed removal rolls back all staged stores; invitation cancellation does not transfer", () => {
    const { storage, w } = init(); createContacts(storage, "lin", w.id).change(a => a.personal.contacts.push(contact("lin")));
    const original = storage.getItem(M.KEY), contacts = storage.getItem("baizhi-v14-contacts"), write = storage.setItem.bind(storage);
    storage.setItem = (k, v) => { if (k === M.KEY) throw Error("quota"); write(k, v); };
    expect(() => createWorkspaceStore(storage).change(s => M.memberAction(s, M.get(s, w.id), "lin", "remove"))).toThrow(/保存失败/);
    expect(storage.getItem(M.KEY)).toBe(original); expect(storage.getItem("baizhi-v14-contacts")).toBe(contacts);
    storage.setItem = write;
    createWorkspaceStore(storage).change(s => M.memberAction(s, M.get(s, w.id), "alice", "remove"));
    expect(M.get(createWorkspaceStore(storage).read(), w.id).ownershipTransfers).toBeUndefined();
  });
  test("legacy type policies migrate existing contacts only and cannot auto-share future records", () => {
    const { storage, s, w } = init();
    w.customerSharing = { lin: true };
    w.contentSharing = { lin: { meetings: { enabled: true, users: ["kevin"], editors: ["kevin"] } } };
    storage.setItem(M.KEY, JSON.stringify(s));
    const legacy = contact("lin"); delete legacy.sharedWith;
    storage.setItem("baizhi-v14-contacts", JSON.stringify({ "workspace:team-eureka:account:lin": { contacts: [legacy], notes: {}, tasks: [] } }));
    createContacts(storage, "lin", w.id).change(a => a.personal.contacts.push({ ...contact("lin"), id: "new" }));
    expect(createContacts(storage, "kevin", w.id).readVisible().personal.contacts.map(c => c.id)).toEqual(["c1"]);
    const next = M.addFile(w, { title: "不继承类型策略" }, "lin");
    expect(next.shared).toEqual([]); expect(M.canEdit(w, next, "kevin")).toBe(false);
    w.status = "expired";
    expect(M.canEdit(w, next, "zhang")).toBe(false);
    expect(() => M.edit(w, next.id, { title: "到期拒绝" })).toThrow(/只读/);
  });
  test("only one team can be created or joined, even if subscription expired", () => {
    const { s, w } = init();
    expect(() => M.acceptInvite(s, "invite-growth")).toThrow(/最多/);
    expect(() => M.create(s, { name: "另一团队", country: "中国", cycle: "month", seats: 2, orderId: "another" })).toThrow(/最多/);
    w.status = "expired"; expect(() => M.assertCanJoinTeam(s)).toThrow(/最多/);
  });
  test("phone source deduplicates same member across channels, CRM wins, transferred origins remain distinct", () => {
    const state = { contacts: [] as Contact[], notes: {}, tasks: [] };
    const a = ingestCustomer(state, contact("lin"), { id: "crm1", crmSystem: "demo", crmId: "1", channel: "crm", verifiedPhone: "+8613800001001", fields: { name: "CRM 周宁" }, updatedAt: "2026-10-10" }, "lin");
    ingestCustomer(state, { ...contact("lin"), id: "phone" }, { id: "phone1", channel: "phone", verifiedPhone: "+86 13800001001", fields: { name: "手机周宁" }, updatedAt: "2026-10-10" }, "lin");
    expect(state.contacts).toHaveLength(1); expect(a.name).toBe("CRM 周宁");
    a.ownerId = "zhang"; a.previousOwnerId = "lin";
    ingestCustomer(state, contact("zhang"), { id: "manual", channel: "manual", verifiedPhone: "+8613800001001", fields: { name: "本人周宁" }, updatedAt: "2026-10-10" }, "zhang");
    expect(state.contacts).toHaveLength(2);
  });
});
