import {test,expect,Page} from '@playwright/test';
test.use({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,timezoneId:'Asia/Shanghai',viewport:{width:1440,height:1000}});
const url='/prototype/one-to-one-reference/team-only-app.html?edition=personal&personal=1';
const enter=async(page:Page,type='schedule')=>{await page.goto(url);await page.locator('[data-widget-all]').click();await page.locator(`[data-thought-category=${type}]`).click();};
const capture=async(page:Page,name:string)=>{if(process.env.PRD_CAPTURE)await page.screenshot({path:`src/prototype/prd/images/${name}.png`});};
test('five type tabs have real counts, direct records and scoped filters',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await enter(page);
 expect(await page.locator('[data-thought-category]').evaluateAll(es=>es.map(e=>(e as HTMLElement).dataset.thoughtCategory))).toEqual(['schedule','todo','inspiration','ledger','other']);await expect(page.locator('[data-thought-category=all],[data-thought-file]')).toHaveCount(0);
 for(const type of ['schedule','todo','inspiration','ledger','other']){await page.locator(`[data-thought-category=${type}]`).click();const count=Number(await page.locator(`[data-thought-category=${type}] em`).textContent());await expect(page.locator('[data-thought-record]')).toHaveCount(count);}
 await page.locator('[data-thought-category=inspiration]').click();await page.locator('#thought-file-search').fill('职责');await expect(page.locator('[data-thought-record]')).toHaveCount(1);await page.locator('[data-thought-record]').click();await expect(page.locator('#thought-record-dialog')).toContainText('专家卡');await page.locator('#thought-record-dialog [data-th=close]').last().click();
 await page.locator('[data-thought-category=ledger]').click();await page.locator('#th-from').fill('2026-08-01');await page.locator('#th-to').fill('2026-08-31');await expect(page.locator('#thought-file-list')).toContainText('报销到账');await expect(page.locator('#thought-file-list')).not.toContainText('客户拜访交通');await page.locator('#th-from').fill('2026-09-01');await expect(page.locator('#thought-file-list')).toContainText('开始日期不能晚于');await page.locator('.th-filters [data-th=clear]').click();
 await page.locator('[data-thought-category=todo]').click();await capture(page,'thoughts');for(const width of [1440,1024,390]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);await expect(page.locator('#thought-toolbar [data-th=new]')).toBeInViewport();}expect(errors).toEqual([]);
});
test('record thought opens existing App/device guidance without creating a record',async({page})=>{
 await enter(page);const before=await page.evaluate(()=>localStorage.getItem('eureka:thoughts:v1'));await page.locator('#thought-toolbar [data-th=new]').click();await expect(page.locator('#ws-dialog')).toContainText('绑定你的设备');await expect(page.locator('#ws-dialog')).toContainText('个人工作空间');await expect(page.locator('#ws-dialog a[href="https://eurekamind.ai/download"]')).toBeVisible();await expect(page.locator('#ws-dialog a[href="https://eurekamind.ai/shop"]')).toBeVisible();await capture(page,'thought-record-guide');await page.locator('#ws-dialog [data-ws-action=close-dialog]').first().click();await expect(page.locator('#thought-workspace')).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('eureka:thoughts:v1'))).toEqual(before);
});
test('editing money, cancel and refresh preserve capture and correct home spending',async({page})=>{
 await enter(page,'ledger');await page.locator('#thought-file-search').fill('客户拜访交通');await page.locator('[data-thought-record]').click();await page.locator('#thought-record-dialog [data-th=edit]').click();await page.locator('#th-edit-form [name=title]').fill('客户交通 · 更新');await page.locator('#th-edit-form [name=amount]').fill('63.50');await page.locator('#th-edit-form [name=detail]').fill('出租车到客户园区');await capture(page,'thought-edit');await page.locator('#thought-record-dialog [data-th=close]').last().click();await expect(page.locator('.th-guard')).toBeVisible();await page.locator('[data-th=continue]').click();await page.locator('#th-edit-form button[type=submit]').click();await expect(page.locator('.th-detail-money')).toContainText('63.50');await page.locator('.th-original summary').click();await expect(page.locator('.th-original')).toContainText('48.00');await page.locator('#thought-record-dialog [data-th=close]').last().click();await page.locator('#home-entry').click();await expect(page.locator('.daily-ledger-total')).toContainText('263.50');await page.reload();await page.locator('[data-widget-all]').click();await page.locator('[data-thought-category=ledger]').click();await page.locator('#thought-file-search').fill('客户交通');await expect(page.locator('[data-thought-record]')).toContainText('63.50');
 await page.locator('[data-thought-record]').click();await page.locator('#thought-record-dialog [data-th=edit]').click();await page.locator('#th-edit-form [name=direction]').selectOption('income');await page.locator('#th-edit-form button[type=submit]').click();await page.locator('#thought-record-dialog [data-th=close]').last().click();await page.locator('#home-entry').click();await expect(page.locator('.daily-ledger-total')).toContainText('200.00');
});
test('todo check completes in place; quick preview/edit stay in thoughts and Details opens full page',async({page})=>{
 await enter(page,'todo');await page.locator('#thought-file-search').fill('发送修订');const row=page.locator('.th-row');const check=row.getByRole('checkbox');await check.click();await expect(check).toHaveAttribute('aria-checked','true');await expect(page.locator('#thought-workspace')).toBeVisible();await check.click();await expect(check).toHaveAttribute('aria-checked','false');
 await page.locator('[data-thought-record]').click();await expect(page.locator('#action-quick-dialog')).toContainText('截止时间');await expect(page.locator('#personal-actions')).toBeHidden();await capture(page,'thought-action-preview');await page.locator('#action-quick-dialog [data-ap=edit]').click();await page.locator('#ap-edit-form [name=title]').fill('发送修订后的报价单');await capture(page,'thought-action-edit');await page.locator('#ap-edit-form button[type=submit]').click();await expect(page.locator('#action-quick-dialog')).not.toBeVisible();await expect(page.locator('[data-thought-record]')).toContainText('报价单');await expect(page.locator('#thought-file-search')).toHaveValue('发送修订');
 await row.locator('[data-th=details]').click();await expect(page.locator('#personal-actions h1')).toContainText('报价单');await page.locator('[data-pa=back]').click();await expect(page.locator('#thought-workspace')).toBeVisible();await page.reload();await page.locator('[data-widget-all]').click();await page.locator('[data-thought-category=todo]').click();await page.locator('#thought-file-search').fill('报价单');await page.locator('[data-thought-record]').click();await page.locator('#action-quick-dialog [data-ap=details]').click();await expect(page.locator('#personal-actions h1')).toContainText('报价单');
});
test('calendar day/week/month allow editing without opening detail and protect unsaved input',async({page})=>{
 await page.goto(url);await page.locator('#todos-entry').click();if(process.env.PRD_CAPTURE){for(const mode of ['day','week','month']){await page.locator(`[data-pa=calendar-mode][data-id=${mode}]`).click();await capture(page,'personal-calendar-'+mode);}}
 for(const mode of ['day','week','month']){await page.locator(`[data-pa=calendar-mode][data-id=${mode}]`).click();await page.locator('[data-pa=quick-edit][data-id=calendar-meeting-review]').click();await expect(page.locator('#action-quick-dialog')).toBeVisible();await expect(page.locator('#personal-actions h1')).toHaveText('日程与待办');await page.locator('#ap-edit-form [name=title]').fill('方案讨论 · '+mode);await page.locator('#ap-edit-form button[type=submit]').click();await expect(page.locator('.pa-list-row').filter({hasText:'方案讨论 · '+mode})).toHaveCount(1);}
 await page.locator('[data-pa=quick-edit][data-id=calendar-todo-demo]').click();await page.locator('#ap-edit-form [name=title]').fill('未保存的待办');await page.keyboard.press('Escape');await expect(page.locator('.ap-guard')).toBeVisible();await page.locator('.ap-guard [data-ap=continue]').click();await expect(page.locator('#ap-edit-form [name=title]')).toHaveValue('未保存的待办');await page.locator('#action-quick-dialog [data-ap=close]').last().click();await page.locator('.ap-guard [data-ap=discard]').click();await expect(page.locator('#personal-actions')).not.toContainText('未保存的待办');
 await page.setViewportSize({width:390,height:844});await page.locator('[data-pa=calendar-mode][data-id=day]').click();await page.locator('[data-pa=quick-edit][data-id=calendar-todo-demo]').click();await expect(page.locator('#action-quick-dialog')).toBeInViewport();expect(await page.locator('#action-quick-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBeTruthy();
});
test('Agent cites the current type and query; failed storage and conflicts preserve input',async({page,context})=>{
 await enter(page,'inspiration');await page.locator('#thought-file-search').fill('给产品演示');await page.locator('#thought-toolbar [data-th=ask]').click();await page.locator('#xiaozhi-send').click();await expect(page.locator('#widget-agent-result')).toContainText('给产品演示');await expect(page.locator('#widget-agent-result')).not.toContainText('客户工作午餐');await page.locator('#xiaozhi-collapse').click();await page.locator('[data-thought-record]').click();await page.locator('#thought-record-dialog [data-th=edit]').click();await page.locator('#th-edit-form [name=title]').fill('保留我的修改');await page.evaluate(()=>{const old=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='eureka:thoughts:v1')throw new Error('quota');return old.call(this,k,v);};});await page.locator('#th-edit-form button[type=submit]').click();await expect(page.locator('.th-error')).toContainText('保存失败');
 const other=await context.newPage();await enter(other,'inspiration');await other.locator('#thought-file-search').fill('给产品演示');await other.locator('[data-thought-record]').click();await other.locator('#thought-record-dialog [data-th=edit]').click();await other.locator('#th-edit-form [name=title]').fill('其他窗口保存');await other.locator('#th-edit-form button[type=submit]').click();await page.locator('#th-edit-form button[type=submit]').click();await expect(page.locator('.th-error')).toContainText('另一页面已更新');await expect(page.locator('#th-edit-form [name=title]')).toHaveValue('保留我的修改');
});

test('quick action editor validates time and preserves drafts on storage failure or another tab edit',async({page,context})=>{
 await enter(page);await page.locator('.th-row [data-th=edit]').first().click();const original=await page.locator('#ap-edit-form [name=title]').inputValue();const start=await page.locator('#ap-edit-form [name=start]').inputValue();await page.locator('#ap-edit-form [name=end]').fill(start);await page.locator('#ap-edit-form button[type=submit]').click();await expect(page.locator('#action-quick-dialog .th-error')).toBeVisible();await expect(page.locator('#action-quick-dialog')).toBeVisible();await page.locator('#action-quick-dialog [data-ap=close]').last().click();await page.locator('.ap-guard [data-ap=discard]').click();
 await page.locator('#thought-file-search').fill(original);await page.locator('.th-row [data-th=edit]').click();await page.locator('#ap-edit-form [name=title]').fill('保留我的日程修改');await page.evaluate(()=>{const old=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='eureka:personal-actions:v1')throw new Error('quota');return old.call(this,k,v);};});await page.locator('#ap-edit-form button[type=submit]').click();await expect(page.locator('#action-quick-dialog .th-error')).toContainText('保存失败');await expect(page.locator('[data-thought-record]')).toContainText(original);
 const other=await context.newPage();await enter(other);await other.locator('#thought-file-search').fill(original);await other.locator('.th-row [data-th=edit]').click();await other.locator('#ap-edit-form [name=title]').fill('另一窗口的新日程');await other.locator('#ap-edit-form button[type=submit]').click();await page.locator('#ap-edit-form button[type=submit]').click();await expect(page.locator('#action-quick-dialog .th-error')).toContainText(/这条记录已更新|另一页面已更新/);await expect(page.locator('#ap-edit-form [name=title]')).toHaveValue('保留我的日程修改');
});
