import {test,expect} from '@playwright/test';
test.use({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,timezoneId:'Asia/Shanghai',viewport:{width:1440,height:1000}});
const url='/prototype/one-to-one-reference/team-only-app.html?edition=personal&personal=1';
const enter=async(page:import('@playwright/test').Page)=>{await page.goto(url);await page.locator('[data-widget-all]').click();};
test('capture index has real counts, direct records, date filters and full-text search',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await enter(page);
 await expect(page.locator('[data-thought-file]')).toHaveCount(0);await expect(page.locator('#thought-toolbar')).not.toContainText('新建日程');
 const count=Number(await page.locator('#thought-all-count').textContent());await expect(page.locator('[data-thought-record]')).toHaveCount(count);
 await page.locator('[data-thought-category=inspiration]').click();await page.locator('#thought-file-search').fill('职责');await expect(page.locator('[data-thought-record]')).toHaveCount(1);await page.locator('[data-thought-record]').click();await expect(page.locator('#thought-record-dialog')).toContainText('专家卡');await page.locator('#thought-record-dialog [data-th=close]').last().click();
 await page.locator('[data-thought-category=all]').click();await page.locator('#th-from').fill('2026-08-01');await page.locator('#th-to').fill('2026-08-31');await expect(page.locator('#thought-file-list')).toContainText('报销到账');await expect(page.locator('#thought-file-list')).not.toContainText('客户拜访交通');
 await page.locator('#th-from').fill('2026-09-01');await expect(page.locator('#thought-file-list')).toContainText('开始日期不能晚于');await page.locator('.th-filters [data-th=clear]').click();
 if(process.env.PRD_CAPTURE)await page.screenshot({path:'src/prototype/prd/images/thoughts.png'});
 for(const width of [1440,1024,390]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);await expect(page.locator('#thought-toolbar [data-th=new]')).toBeInViewport();}
 expect(errors).toEqual([]);
});
test('editing, cancellation, money, capture provenance, refresh and home widgets share real data',async({page})=>{
 await enter(page);await page.locator('#thought-file-search').fill('客户拜访交通');await page.locator('[data-thought-record]').click();await page.locator('#thought-record-dialog [data-th=edit]').click();
 await page.locator('#th-edit-form [name=title]').fill('客户交通 · 更新');await page.locator('#th-edit-form [name=amount]').fill('63.50');await page.locator('#th-edit-form [name=detail]').fill('出租车到客户园区');
 if(process.env.PRD_CAPTURE)await page.screenshot({path:'src/prototype/prd/images/thought-edit.png'});
 await page.locator('#thought-record-dialog [data-th=close]').last().click();await expect(page.locator('.th-guard')).toBeVisible();await page.locator('[data-th=continue]').click();await page.locator('#th-edit-form button[type=submit]').click();await expect(page.locator('.th-detail-money')).toContainText('63.50');await page.locator('.th-original summary').click();await expect(page.locator('.th-original')).toContainText('48.00');await page.locator('#thought-record-dialog [data-th=close]').last().click();
 await page.locator('#home-entry').click();await expect(page.locator('.daily-ledger-total')).toContainText('263.50');await page.reload();await page.locator('[data-widget-all]').click();await page.locator('#thought-file-search').fill('客户交通');await expect(page.locator('[data-thought-record]')).toContainText('63.50');await page.locator('[data-thought-record]').click();await page.locator('#thought-record-dialog [data-th=edit]').click();await page.locator('#th-edit-form [name=title]').fill('丢弃修改');await page.locator('#thought-record-dialog [data-th=close]').last().click();await page.locator('[data-th=discard]').click();await expect(page.locator('[data-thought-record]')).not.toContainText('丢弃修改');
 await page.locator('#thought-toolbar [data-th=new]').click();await page.locator('#th-edit-form [name=title]').fill('测试报销');await page.locator('#th-edit-form [name=type]').selectOption('ledger');await page.locator('#th-edit-form [name=direction]').selectOption('income');await page.locator('#th-edit-form [name=amount]').fill('200');await page.locator('#th-edit-form button[type=submit]').click();await page.locator('#thought-record-dialog [data-th=close]').last().click();await page.locator('#home-entry').click();await expect(page.locator('.daily-ledger-total')).toContainText('263.50');
});
test('action detail round-trip keeps filters and edits canonical record; Agent uses filtered captures',async({page})=>{
 await enter(page);await page.locator('#thought-file-search').fill('发送修订');await page.locator('[data-thought-record]').click();await expect(page.locator('#personal-actions h1')).toContainText('发送修订');await page.locator('[data-pa=edit]').click();await page.locator('#pa-edit-form [name=title]').fill('发送修订后的报价单');await page.locator('#pa-edit-form button[type=submit]').click();await page.locator('[data-pa=back]').click();await expect(page.locator('#thought-workspace')).toBeVisible();await expect(page.locator('#thought-file-search')).toHaveValue('发送修订');await expect(page.locator('[data-thought-record]')).toContainText('报价单');
 await page.locator('[data-thought-record]').click();await page.locator('#personal-actions [data-pa=agent]').click();await page.locator('#pa-prompt').fill('明天 14:00 创建待办「保护草稿」');await page.locator('#pa-prompt').press('Enter');await page.locator('[data-pa=back]').click();await expect(page.locator('.pa-dialog')).toContainText('保留这次修改');await page.locator('.pa-dialog [data-pa=discard]').click();await expect(page.locator('#thought-workspace')).toBeVisible();
 await page.locator('#thought-file-search').fill('客户工作午餐');await page.locator('#thought-toolbar [data-th=ask]').click();await expect(page.locator('#xiaozhi-rail')).toBeVisible();await expect(page.locator('#xiaozhi-widget-context')).toContainText('1 条闪念');await page.locator('#xiaozhi-send').click();await expect(page.locator('#widget-agent-result')).toContainText('客户工作午餐');await expect(page.locator('#widget-agent-result')).not.toContainText('报价单');
});
test('failed storage and concurrent changes preserve editor input',async({page,context})=>{
 await enter(page);await page.locator('#thought-file-search').fill('给产品演示');await page.locator('[data-thought-record]').click();await page.locator('#thought-record-dialog [data-th=edit]').click();await page.locator('#th-edit-form [name=title]').fill('保留我的修改');
 await page.evaluate(()=>{const old=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='eureka:thoughts:v1')throw new Error('quota');return old.call(this,k,v);};});await page.locator('#th-edit-form button[type=submit]').click();await expect(page.locator('.th-error')).toContainText('保存失败');await expect(page.locator('#th-edit-form [name=title]')).toHaveValue('保留我的修改');
 const other=await context.newPage();await enter(other);await other.locator('#thought-file-search').fill('给产品演示');await other.locator('[data-thought-record]').click();await other.locator('#thought-record-dialog [data-th=edit]').click();await other.locator('#th-edit-form [name=title]').fill('其他窗口保存');await other.locator('#th-edit-form button[type=submit]').click();await expect(page.locator('.th-error')).toContainText('另一页面已更新');await page.locator('#th-edit-form button[type=submit]').click();await expect(page.locator('.th-error')).toContainText('另一页面已更新');await expect(page.locator('#th-edit-form [name=title]')).toHaveValue('保留我的修改');
});
