const assert=require('node:assert/strict');
require('../assets/workspace-model.js');
const M=globalThis.WorkspaceModel;
const s=M.seed(),w=M.get(s,'team-eureka'),other=M.get(s,'team-design');
assert.equal(M.visible(w).length,3);
assert(!M.visible(w).some(f=>f.id==='team-private'));
assert.throws(()=>M.getFile(w,'team-private'),/访问权限/);
assert.throws(()=>M.edit(w,'team-customer',{summary:'override'}),/所有者/);
assert.throws(()=>M.invite(w,'guest@example.com','member','kevin'),/管理员/);
assert.throws(()=>M.invite(w,'not-email'),/有效/);
assert.throws(()=>M.invite(w,'a@example.com,b@example.com,c@example.com'),/不足/);
assert.equal(M.usedSeats(w),4);
const [inv]=M.invite(w,'guest@example.com');assert.equal(M.usedSeats(w),5);
assert.throws(()=>M.invite(w,'guest@example.com'),/已加入/);
M.memberAction(s,w,inv.id,'accept');assert.equal(inv.status,'active');
M.memberAction(s,w,inv.id,'remove');assert.equal(M.usedSeats(w),4);assert.equal(w.seats,6);
M.seats(w,4);assert.equal(w.seats,6);assert.equal(w.pendingSeats,4);
assert.throws(()=>M.invite(w,'blocked@example.com'),/不足/);
M.seats(w,8);assert.equal(w.seats,8);assert.equal(w.pendingSeats,null);
assert.throws(()=>M.seats(w,3),/4–50/);
const own=M.addFile(w,{title:'新记录'});assert.deepEqual(own.shared,[]);
M.share(w,own.id,['kevin']);assert(M.visible(w,'kevin').some(f=>f.id===own.id));
M.share(w,own.id,[]);assert(!M.visible(w,'kevin').some(f=>f.id===own.id));
assert.throws(()=>M.share(w,own.id,['outsider']),/有效成员/);
const exported=M.exportFile(w,own.id);const imported=M.importFile(other,exported);
assert.notEqual(imported.id,own.id);assert.equal(imported.owner,M.SELF);assert.deepEqual(imported.shared,[]);
M.edit(other,imported.id,{summary:'changed'});assert.notEqual(own.summary,imported.summary);
M.trash(w,own.id);assert(!M.visible(w).includes(own));M.trash(w,own.id,true);assert(M.visible(w).includes(own));
const device=s.devices.find(d=>d.id==='dev-personal');s.activeId=w.id;
assert.equal(M.sync(s,device.id).space.id,'personal');
M.bind(s,device.id,w.id);s.activeId='personal';assert.equal(M.sync(s,device.id).space.id,w.id);
assert.throws(()=>M.bind(s,'dev-team','personal'),/自己的设备/);
const credits=w.credits.used;M.ask(w,'整理任务',own.id);assert.equal(w.credits.used,credits+200);assert.equal(M.get(s,'personal').credits.used,0);
assert.throws(()=>M.ask(w,'私有文件','team-private'),/访问权限/);
w.credits.total=w.credits.used;assert.throws(()=>M.ask(w,'分析'),/不足/);
w.status='expired';assert(M.visible(w).length);assert.throws(()=>M.addFile(w,{title:'no'}),/只读/);assert.throws(()=>M.invite(w,'again@example.com'),/只读/);assert.throws(()=>M.ask(w,'分析'),/只读/);
const created=M.create(s,{name:'测试团队',country:'中国',cycle:'month',seats:2,orderId:'idem-1'});
assert.equal(created.files.length,0);assert.equal(created.members.length,1);assert.equal(M.create(s,{name:'测试团队',country:'中国',cycle:'month',seats:2,orderId:'idem-1'}).id,created.id);
assert.throws(()=>M.memberAction(s,created,M.SELF,'role','member'),/至少/);
const joined=M.acceptInvite(s,'invite-growth');assert.equal(M.admin(joined),false);assert.equal(M.visible(joined).length,1);
assert.throws(()=>M.acceptInvite(s,'invite-growth'),/已处理/);
console.log('PASS: workspace isolation, privacy, roles, seats, device binding, credits, lifecycle and idempotent creation.');
